CREATE TABLE thoigian
(
    thoigian_id   INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    thoigian_loai VARCHAR(255),
    thoigian_mota VARCHAR(255),
    created_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    modified_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleted_at    TIMESTAMP,
    CONSTRAINT pk_thoigian PRIMARY KEY (thoigian_id)
);