CREATE TABLE tacnhan
(
    tacnhan_id   INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tacnhan_ten  VARCHAR(255),
    tacnhan_mota VARCHAR(255),
    created_at   TIMESTAMP WITHOUT TIME ZONE,
    modified_at  TIMESTAMP WITHOUT TIME ZONE,
    deleted_at   TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_tacnhan PRIMARY KEY (tacnhan_id)
);