CREATE TABLE nguoidung
(
    nguoidung_id       INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nguoidung_dangnhap VARCHAR(255),
    nguoidung_matkhau  VARCHAR(255),
    nguoidung_hoten    VARCHAR(255),
    nguoidung_donvi    VARCHAR(255),
    nguoidung_anh      VARCHAR(255),
    nguoidung_sdt      VARCHAR(255),
    nguoidung_diachi   VARCHAR(255),
    nguoidung_sofax    VARCHAR(255),
    nguoidung_email    VARCHAR(255),
    nguoidung_mota     VARCHAR(255),
    created_at         TIMESTAMP WITHOUT TIME ZONE,
    modified_at        TIMESTAMP WITHOUT TIME ZONE,
    deleted_at         TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_nguoidung PRIMARY KEY (nguoidung_id)
);