CREATE TABLE phuongthuc_baohanh
(
    phuongthuc_baohanh_id      INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    phuongthuc_baohanh_noidung VARCHAR(255),
    phuongthuc_baohanh_mota    VARCHAR(255),
    created_at                 TIMESTAMP WITHOUT TIME ZONE,
    modified_at                TIMESTAMP WITHOUT TIME ZONE,
    deleted_at                 TIMESTAMP WITHOUT TIME ZONE,
    baohanh_id                 INTEGER,
    CONSTRAINT pk_phuongthuc_baohanh PRIMARY KEY (phuongthuc_baohanh_id)
);
