CREATE TABLE baogia_khachhang
(
    baogia_khachhang_id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at          TIMESTAMP WITHOUT TIME ZONE,
    modified_at         TIMESTAMP WITHOUT TIME ZONE,
    deleted_at          TIMESTAMP WITHOUT TIME ZONE,
    khachhang_id        INTEGER,
    baogia_id           INTEGER,
    CONSTRAINT pk_baogia_khachhang PRIMARY KEY (baogia_khachhang_id)
);
