CREATE TABLE tuvan
(
    tuvan_id    INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tuvan_ten   VARCHAR(255),
    tuvan_sdt   VARCHAR(255),
    tuvan_email VARCHAR(255),
    created_at  TIMESTAMP WITHOUT TIME ZONE,
    modified_at TIMESTAMP WITHOUT TIME ZONE,
    deleted_at  TIMESTAMP WITHOUT TIME ZONE,
    danhxung_id INTEGER,
    CONSTRAINT pk_tuvan PRIMARY KEY (tuvan_id)
);