CREATE TABLE tuvan_baohanh
(
    tuvan_baohanh_id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at       TIMESTAMP WITHOUT TIME ZONE,
    modified_at      TIMESTAMP WITHOUT TIME ZONE,
    deleted_at       TIMESTAMP WITHOUT TIME ZONE,
    baohanh_baogia_id       INTEGER,
    tuvan_id         INTEGER,
    CONSTRAINT pk_tuvan_baohanh PRIMARY KEY (tuvan_baohanh_id)
);
