CREATE TABLE phuongthuc_thanhtoan
(
    phuongthuc_thanhtoan_id   INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    phuongthuc_thanhtoan_ten  VARCHAR(255),
    phuongthuc_thanhtoan_mota VARCHAR(255),
    created_at                TIMESTAMP WITHOUT TIME ZONE,
    modified_at               TIMESTAMP WITHOUT TIME ZONE,
    deleted_at                TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_phuongthuc_thanhtoan PRIMARY KEY (phuongthuc_thanhtoan_id)
);