CREATE TABLE baogia_phuongthucthanhtoan
(
    baogia_phuongthucthanhtoan_id           INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    baogia_phuongthucthanhtoan_giatri       DECIMAL,
    baogia_phuongthucthanhtoan_giatriconlai DECIMAL,
    baogia_phuongthucthanhtoan_mota         VARCHAR(255),
    baogia_phuongthucthanhtoan_lanthanhtoan INTEGER,
    baogia_phuongthucthanhtoan_thoihan      TIMESTAMP WITHOUT TIME ZONE,
    created_at                              TIMESTAMP WITHOUT TIME ZONE,
    modified_at                             TIMESTAMP WITHOUT TIME ZONE,
    deleted_at                              TIMESTAMP WITHOUT TIME ZONE,
    thoigian_id                             INTEGER,
    baogia_id                               INTEGER,
    phuongthuc_thanhtoan_id                 INTEGER,
    CONSTRAINT pk_baogia_phuongthucthanhtoan PRIMARY KEY (baogia_phuongthucthanhtoan_id)
);



