CREATE TABLE chucnang_hangmuc
(
    chucnang_hangmuc_id  INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    chucnang_hangmuc_gia DECIMAL,
    created_at           TIMESTAMP WITHOUT TIME ZONE,
    modified_at          TIMESTAMP WITHOUT TIME ZONE,
    deleted_at           TIMESTAMP WITHOUT TIME ZONE,
    hangmuc_id           INTEGER,
    chucnang_id          INTEGER,
    baogia_id            INTEGER,
    phanmem_id           INTEGER,
    nhomchucnang_id      INTEGER,
    CONSTRAINT pk_chucnang_hangmuc PRIMARY KEY (chucnang_hangmuc_id)
);

