CREATE TABLE thongso
(
    thongso_id  INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    thongso_ma  VARCHAR(255),
    thongso_ten VARCHAR(255),
    thongso_mota VARCHAR(255),
    created_at  TIMESTAMP WITHOUT TIME ZONE,
    modified_at TIMESTAMP WITHOUT TIME ZONE,
    deleted_at  TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_thongso PRIMARY KEY (thongso_id)
);