CREATE TABLE sanpham_baogia
(
    sanpham_baogia_id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at        TIMESTAMP WITHOUT TIME ZONE,
    modified_at       TIMESTAMP WITHOUT TIME ZONE,
    deleted_at        TIMESTAMP WITHOUT TIME ZONE,
    sanpham_id        INTEGER,
    baogia_id         INTEGER,
    CONSTRAINT pk_sanpham_baogia PRIMARY KEY (sanpham_baogia_id)
);