CREATE TABLE sanpham_tskt
(
    sanpham_tskt_id     INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    sanpham_tskt_giatri VARCHAR(255),
    created_at          TIMESTAMP WITHOUT TIME ZONE,
    modified_at         TIMESTAMP WITHOUT TIME ZONE,
    deleted_at          TIMESTAMP WITHOUT TIME ZONE,
    sanpham_baogia_id   INTEGER,
    thongso_group_id    INTEGER,
    thongso_id          INTEGER,
    CONSTRAINT pk_sanpham_tskt PRIMARY KEY (sanpham_tskt_id)
);