CREATE TABLE sanpham_maychu
(
    sanpham_maychu_id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at        TIMESTAMP WITHOUT TIME ZONE,
    modified_at       TIMESTAMP WITHOUT TIME ZONE,
    deleted_at        TIMESTAMP WITHOUT TIME ZONE,
    sanpham_baogia_id INTEGER,
    maychu_id         INTEGER,
    CONSTRAINT pk_sanpham_maychu PRIMARY KEY (sanpham_maychu_id)
);