CREATE TABLE kythuat_congnghe
(
    kythuat_congnghe_id      INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    kythuat_congnghe_noidung VARCHAR(255),
    kythuat_congnghe_giatri  VARCHAR(255),
    created_at               TIMESTAMP WITHOUT TIME ZONE,
    modified_at              TIMESTAMP WITHOUT TIME ZONE,
    deleted_at               TIMESTAMP WITHOUT TIME ZONE,
    baogia_id                INTEGER,
    sanpham_id               INTEGER,
    CONSTRAINT pk_kythuat_congnghe PRIMARY KEY (kythuat_congnghe_id)
);
