CREATE TABLE bienbanhop
(
    bienbanhop_id         INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    bienbanhop_ten        VARCHAR(255),
    bienbanhop_diadiem    VARCHAR(255),
    bienbanhop_giobatdau  TIMESTAMP WITHOUT TIME ZONE,
    bienbanhop_gioketthuc TIMESTAMP WITHOUT TIME ZONE,
    bienbanhop_mota       VARCHAR(255),
    nguoidung_id          INTEGER,
    created_at            TIMESTAMP WITHOUT TIME ZONE,
    modified_at           TIMESTAMP WITHOUT TIME ZONE,
    deleted_at            TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_bienbanhop PRIMARY KEY (bienbanhop_id)
);
