CREATE TABLE bienban_ketluan
(
    bbketluan_id   INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    bienbanhop_id  INTEGER,
    bbketluan_mota VARCHAR(255),
    created_at     TIMESTAMP WITHOUT TIME ZONE,
    modified_at    TIMESTAMP WITHOUT TIME ZONE,
    deleted_at     TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_bienban_ketluan PRIMARY KEY (bbketluan_id)
);
