CREATE TABLE if not exists sanpham_hangmuc
(
    sanpham_hangmuc_id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    sanpham_id INTEGER,
    hangmuc_id INTEGER,
    created_at     TIMESTAMP WITHOUT TIME ZONE,
    modified_at    TIMESTAMP WITHOUT TIME ZONE,
    deleted_at     TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_sanpham_hangmuc PRIMARY KEY (sanpham_hangmuc_id)
);
