CREATE TABLE goibaogia
(
    goibaogia_id   INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    goibaogia_ten  VARCHAR(255),
    goibaogia_mota VARCHAR(255),
    created_at     TIMESTAMP WITHOUT TIME ZONE,
    modified_at    TIMESTAMP WITHOUT TIME ZONE,
    deleted_at     TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_goibaogia PRIMARY KEY (goibaogia_id)
);
