CREATE TABLE khachhang
(
    khachhang_id   INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    khachhang_ten  VARCHAR(255),
    khachhang_mota VARCHAR(255),
    created_at     TIMESTAMP WITHOUT TIME ZONE,
    modified_at    TIMESTAMP WITHOUT TIME ZONE,
    deleted_at     TIMESTAMP WITHOUT TIME ZONE,
    danhxung_id    INTEGER,
    CONSTRAINT pk_khachhang PRIMARY KEY (khachhang_id)
);