CREATE TABLE hangmuc
(
    hangmuc_id      INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    hangmuc_ten     VARCHAR(255),
    hangmuc_gia     DECIMAL,
    hangmuc_soluong INTEGER,
    hangmuc_mota    VARCHAR(255),
    created_at      TIMESTAMP WITHOUT TIME ZONE,
    modified_at     TIMESTAMP WITHOUT TIME ZONE,
    deleted_at      TIMESTAMP WITHOUT TIME ZONE,
    donvitinh_id    INTEGER,
    CONSTRAINT pk_hangmuc PRIMARY KEY (hangmuc_id)
);