CREATE TABLE baohanh
(
    baohanh_id   INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    baohanh_mota VARCHAR(255),
    created_at   TIMESTAMP WITHOUT TIME ZONE,
    modified_at  TIMESTAMP WITHOUT TIME ZONE,
    deleted_at   TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_baohanh PRIMARY KEY (baohanh_id)
);