CREATE TABLE sanpham
(
    sanpham_id   INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    sanpham_ten  VARCHAR(255),
    sanpham_mota VARCHAR(255),
    created_at   TIMESTAMP WITHOUT TIME ZONE,
    modified_at  TIMESTAMP WITHOUT TIME ZONE,
    deleted_at   TIMESTAMP WITHOUT TIME ZONE,
    baohanh_id   INTEGER,
    CONSTRAINT pk_sanpham PRIMARY KEY (sanpham_id)
);