CREATE TABLE nhomchucnang
(
    nhomchucnang_id   INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nhomchucnang_ten  VARCHAR(255),
    nhomchucnang_mota VARCHAR(255),
    created_at        TIMESTAMP WITHOUT TIME ZONE,
    modified_at       TIMESTAMP WITHOUT TIME ZONE,
    deleted_at        TIMESTAMP WITHOUT TIME ZONE,
    hangmuc_id        INTEGER,
    CONSTRAINT pk_nhomchucnang PRIMARY KEY (nhomchucnang_id)
);