export const PATH_CUSC_QUOTE = `${process.env.NEXT_PUBLIC_API}api/cusc-quote/v1`;

export const PATHS = {
  THONGSO_PM: PATH_CUSC_QUOTE + "/thongso",
  GR_THONGSO: PATH_CUSC_QUOTE + "/thongsogroup",
  HANGMUC_PM: PATH_CUSC_QUOTE + "/hangmuc",
  PHANMEMMAYCHUCHITIET: PATH_CUSC_QUOTE + "phanmemmaychuchitiet",
  PAYMENT: PATH_CUSC_QUOTE + "/phuongthucthanhtoan",
  GetALL_Report: PATH_CUSC_QUOTE + "/bienbanhop",
  AGENT_USED: PATH_CUSC_QUOTE + "/tacnhan",
  ADVISE: PATH_CUSC_QUOTE + "/tuvan",
  PRODUCT_PACKAGE: PATH_CUSC_QUOTE + "/goibaogia",
  QUOTE: PATH_CUSC_QUOTE + "/baogia",
  Report_ingredient: PATH_CUSC_QUOTE + `/bienbanthanhphan`,
  Report_Conten: PATH_CUSC_QUOTE + `/bienbannoidung`,
  Report_Conclude: PATH_CUSC_QUOTE + `/bienbanketluan`,
  USER: PATH_CUSC_QUOTE + "/nguoidung",
  FUNCTION_GROUP: PATH_CUSC_QUOTE + "/nhomchucnang",
  MAYCHU: PATH_CUSC_QUOTE + "/maychu",
  NHOMCHUCNANG: PATH_CUSC_QUOTE + "/nhomchucnang",
  CHUCNANG: PATH_CUSC_QUOTE + "/chucnang",
  PHANMEM_TSKT: PATH_CUSC_QUOTE + "/sanphamtskt",
  CONTEN: PATH_CUSC_QUOTE + "/noidung",
  DONVITINH: PATH_CUSC_QUOTE + "/donvitinh",
  Get_Report: PATH_CUSC_QUOTE + `/bienbanhop`,
  WARRANTY_SERVICE: PATH_CUSC_QUOTE + "/dichvubaohanh",
  WARRANTY_TERMS: PATH_CUSC_QUOTE + "/dieukhoanbaohanh",
  SOFTWARE_SYSTEM: PATH_CUSC_QUOTE + `/phanmem`,
  CATEGORY_SYSTEM: PATH_CUSC_QUOTE + `/hangmuc`,
  QUOTE_DETAIL: PATH_CUSC_QUOTE + `/chitietbaogia`,
  CUSTOMERS: PATH_CUSC_QUOTE + `/khachhang`,
  WARRANTY_METHOD: PATH_CUSC_QUOTE + `/phuongthucbaohanh`,
  WARRANTY: PATH_CUSC_QUOTE + "/baohanh",
  FUNCTION_CATEGORY: PATH_CUSC_QUOTE + '/chucnanghangmuc',
  PRODUCT: PATH_CUSC_QUOTE + "/sanpham",
  BAOHANHBAOGIA: PATH_CUSC_QUOTE + "/baohanhbaogia",
  KYTHUATCONGNGHE: PATH_CUSC_QUOTE + "/kythuatcongnghe",
  Report_Download: PATH_CUSC_QUOTE + '/word',
  BAOGIAKHACHHANG: PATH_CUSC_QUOTE + "/baogiakhachhang",
  TUVANBAOHANH: PATH_CUSC_QUOTE + "/tuvanbaohanh",
  WORDBANGBAOGIA: PATH_CUSC_QUOTE + "/word/bangbaogia",
  PRODUCTQUOTE: PATH_CUSC_QUOTE + "/sanphambaogia", 
  PRODUCTSEVER: PATH_CUSC_QUOTE + "/sanphammaychu", 
  PRODUCTSEVERDETAIL: PATH_CUSC_QUOTE + "/sanphammaychuchitiet", 
  TECHNOLOGYCATE: PATH_CUSC_QUOTE + "/kythuatcongnghedanhmuc", 
  CATE: PATH_CUSC_QUOTE + "/danhmuc", 
  PRODUCTCATEGORYS : PATH_CUSC_QUOTE + "/sanphamhangmuc",  
  NHOMCHUCNANGTACNHAN : PATH_CUSC_QUOTE + "/nhomchucnangtacnhan",  
};
